syntax on
filetype plugin on

set fenc=utf-8
set hidden
set autoread
set showcmd

" Indentation
set autoindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
set smarttab
set list
set listchars=tab:>-,trail:-,extends:>,precedes:<,nbsp:%
" format
set formatoptions=q
" Views
set title
set number
set relativenumber
set cursorline
set showmatch
set laststatus=2
set statusline=%F%m\ %<[%{&fenc!=''?&fenc:&enc}]\ [%Y]\ [ln:%l,col:%v]
set showtabline=2
" Controls
set mouse=a
set whichwrap=b,s,h,l,<,>,[,],~
" Search
set hlsearch
set incsearch
set smartcase
set ignorecase
" Split
set splitbelow
set splitright
" Backspace
set backspace=indent,eol,start
" Menu
set wildmenu
set wildmode=longest:full,full

" .viminfo
set viminfo+=n~/.local/share/vim/viminfo

" encoding
set encoding=utf-8
set fileencodings=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936

" git commit prefix
augroup gitabbr
  autocmd!
  " ✨ fe: Introduce new features.
  autocmd FileType gitcommit iabbrev fe :sparkles:
  " 🐛 bu: Fix a bug.
  autocmd FileType gitcommit iabbrev bu :bug:
  " 🩹 ad: Simple fix for a non-critical issue.
  autocmd FileType gitcommit iabbrev ad :adhesive_bandage:
  " ♻️ re: Refactor code.
  autocmd FileType gitcommit iabbrev re :recycle:
  " 💥 bo: Introduce breaking changes.
  autocmd FileType gitcommit iabbrev bo :boom:
  " 🔥 rm: Remove code or files.
  autocmd FileType gitcommit iabbrev rm :fire:
  " 🎨 fo: Improve structure / format of the code.
  autocmd FileType gitcommit iabbrev fo :art:
  " 💄 ui: Add or update the UI and style files.
  autocmd FileType gitcommit iabbrev ui :lipstick:
  " 🔧 co: Add or update configuration files.
  autocmd FileType gitcommit iabbrev co :wrench:
  " 📝 do: Add or update documentation.
  autocmd FileType gitcommit iabbrev do :memo:
  " ⬆️ up: Upgrade dependencies.
  autocmd FileType gitcommit iabbrev up :arrow_up:
augroup END
