shell = "zsh"

apply = ["defer"]

[templates]
defer = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer -a -t0.01 source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"
defer0 = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer -a source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"

[plugins]

####################
# eager
####################

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]
profiles = ["eager"]

[plugins.lazy]
local = "~/.config/zsh"
use = ["lazy.zsh"]
profiles = ["eager"]

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
profiles = ["lazy"]

####################
# lazy
####################
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
dir = "src"
apply = ["fpath"]
profiles = ["lazy"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
profiles = ["lazy"]


[plugins.zeno]
github = "yuki-yano/zeno.zsh"
hooks.pre = """
export ZENO_HOME="$(mktemp -d -t zeno.XXXXXX)"
export ZENO_CONFIG_HOME="$XDG_CONFIG_HOME/zeno"
export ZENO_SCRIPT_DIR="$ZENO_CONFIG_HOME/scripts"
export ZENO_ENABLE_SOCK=1
# export ZENO_DISABLE_BUILTIN_COMPLETION=1
export ZENO_GIT_CAT="bat --color=always"
export ZENO_GIT_TREE="eza --tree"

# zsh-defer -a -t0.01 "$ZENO_CONFIG_HOME/config.ts"
"""
hooks.post = """
__zeno_bindkey() {
    bindkey ' '  zeno-auto-snippet
    bindkey '^M' zeno-auto-snippet-and-accept-line
    bindkey '^P' zeno-completion
    bindkey '^X '  zeno-insert-space
    bindkey '^X^M' accept-line
}
zsh-defer -a -t0.01 __zeno_bindkey

# __zeno_chpwd() {
#     "$ZENO_CONFIG_HOME/config.ts"
#     zeno-restart-server
# }
# add-zsh-hook chpwd __zeno_chpwd
"""
profiles = ["lazy"]

# local
[plugins.compinit]
inline = """
autoload -Uz compinit
zsh-defer -a -t0.01 compinit -d "$XDG_STATE_HOME/zcompdump"
"""
profiles = ["lazy"]
