shell = "zsh"

apply = ["defer"]

[templates]
defer = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer -a -t0.01 source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"
defer0 = "{{ hooks | get: \"pre\" | nl }}{% for file in files %}zsh-defer -a source \"{{ file }}\"\n{% endfor %}{{ hooks | get: \"post\" | nl }}"

[plugins]

####################
# eager
####################

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]
profiles = ["eager"]

[plugins.lazy]
local = "~/.config/zsh"
use = ["lazy.zsh"]
profiles = ["eager"]

####################
# lazy
####################

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
dir = "src"
apply = ["fpath"]
profiles = ["lazy"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
profiles = ["lazy"]

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
profiles = ["lazy"]

[plugins.zeno]
github = "yuki-yano/zeno.zsh"
hooks.pre = """
export ZENO_ENABLE_SOCK=1
# export ZENO_DISABLE_BUILTIN_COMPLETION=1
export ZENO_GIT_CAT="bat --color=always"
export ZENO_GIT_TREE="eza --tree"

# zsh-defer -a -t0.01 "$ZENO_CONFIG_HOME/config.ts" # [TODO] configファイルの動的生成
"""
hooks.post = """
__zeno_bindkey() {
    bindkey ' '  zeno-auto-snippet
}
zsh-defer -a -t0.01 __zeno_bindkey
"""
profiles = ["lazy"]

# local
[plugins.compinit]
inline = """
autoload -Uz compinit
zsh-defer -a -t0.01 compinit -d "$XDG_STATE_HOME/zcompdump"
"""
profiles = ["lazy"]
