# ref
# starship configuration reference: https://starship.rs/config/
# inspired by Pastel Powerline Preset: https://starship.rs/presets/pastel-powerline.html
# nerd font cheet sheet: https://www.nerdfonts.com/cheat-sheet
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:1_bg)\
[󰯉 ](bg:1_bg fg:1_fg)\
[](bg:2_bg fg:1_bg)\
$directory\
[](bg:3_bg fg:2_bg)\
$git_branch\
$git_status\
[](bg:4_bg fg:3_bg)\
$golang\
$nodejs\
[](bg:5_bg fg:4_bg)\
$time\
[](bg:6_bg fg:5_bg)\
$cmd_duration\
[](fg:6_bg)\
\n$character"""

# Disable the blank line at the start of the prompt
add_newline = false

palette = "eyemono"

[palettes.eyemono]
1_bg = '#FF4FDB'
2_bg = '#B274FF'
3_bg = '#08C6E9'
4_bg = '#17EDC6'
5_bg = '#85E33C'
6_bg = '#EEF300'
1_fg = '#191E1F'
2_fg = '#191E1F'
3_fg = '#191E1F'
4_fg = '#191E1F'
5_fg = '#191E1F'
6_fg = '#191E1F'

[directory]
style = "bg:2_bg fg:2_fg"
format = "[  $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " "

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""

[git_branch]
style = "bg:3_bg fg:3_fg"
format = '[  $branch ]($style)'

[git_status]
style = "bg:3_bg fg:3_fg"
format = '[$all_status$ahead_behind]($style)'
conflicted = ' '
stashed = ' '
deleted = ' '
renamed = '󰘎 '
modified = ' '
staged = ' $count '
untracked = ' '
ahead = ' ${count} '
behind = ' ${count} '
diverged = ' ${ahead_count}  ${behind_count} '
up_to_date = ' '

[golang]
symbol = ""
style = "bg:4_bg fg:4_fg"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:4_bg fg:4_fg"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"             # Hour:Minute Format
style = "bg:5_bg fg:5_fg"
format = '[  $time ]($style)'

[cmd_duration]
min_time = 500
style = "bg:6_bg fg:6_fg"
format = "[  $duration ]($style)"
