[scriptEnv]
XDG_CONFIG_HOME = "$HOME/.config"
XDG_DATA_HOME = "$HOME/.local/share"
XDG_STATE_HOME = "$HOME/.local/state"
XDG_CACHE_HOME = "$HOME/.cache"
AQUA_ROOT_DIR = "$XDG_DATA_HOME/aquaproj-aqua"
AQUA_CONFIG_DIR = "$XDG_CONFIG_HOME/aquaproj-aqua"