snippets:
  - name: git
    keyword: g
    snippet: git
  - name: git add
    keyword: ga
    snippet: git add
  - name: git commit
    keyword: gc
    snippet: git commit
  - name: git push
    keyword: ps
    snippet: git push
