snippets:
  # git
  - name: git
    keyword: g
    snippet: git

  # git add
  - name: git aa
    keyword: aa
    snippet: add -vA
    context:
      lbuffer: ^git\s

  # git branch
  - name: git b
    keyword: b
    snippet: branch
    context:
      lbuffer: ^git\s

  # git commit
  - name: git c
    keyword: c
    snippet: commit
    context:
      lbuffer: ^git\s
  - name: git cam
    keyword: cam
    snippet: commit --amend --no-edit
    context:
      lbuffer: ^git\s

  # git fetch
  - name: git f
    keyword: f
    snippet: fetch
    context:
      lbuffer: ^git\s

  # git pull
  - name: git pl
    keyword: pl
    snippet: pull
    context:
      lbuffer: ^git\s

  # git push
  - name: git ps
    keyword: ps
    snippet: push
    context:
      lbuffer: ^git\s
  - name: git psu
    keyword: psu
    snippet: push -u origin HEAD
    context:
      lbuffer: ^git\s

  # git status
  - name: git s
    keyword: s
    snippet: status
    context:
      lbuffer: ^git\s

  # git switch
  - name: git sw
    keyword: sw
    snippet: switch
    context:
      lbuffer: ^git\s

  # docker
  - name: docker
    keyword: d
    snippet: docker

  # docker-compose
  - name: docker compose
    keyword: c
    snippet: compose
    context:
      lbuffer: ^docker\s
